AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  tp-api

  Sample SAM Template for tp-api

Parameters:
  Env:
    Type: String
    Default: sandbox
  ImageBucketName:
    Type: String
    Default: telephone-pictionary-staging
  OpenAIAPIKey:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.11
    Environment:
      Variables:
        TP_ENV: !Ref Env
        OPENAI_API_KEY: !Ref OpenAIAPIKey
        TP_IMAGE_BUCKET_NAME: !Ref ImageBucketName
        LOG_LEVEL: INFO

Resources:
  TelephonePictionaryAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  APIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub telephone-pictionary-${Env}
      CodeUri: src
      Handler: app.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ImageBucketName
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref TelephonePictionaryAPI
            Path: /hello
            Method: GET
        SubmitPrompt:
          Type: Api
          Properties:
            RestApiId: !Ref TelephonePictionaryAPI
            Path: /game/{game_id}/prompt
            Method: POST

Outputs:
  TelephonePictionaryAPI:
    Description: "API Gateway endpoint URL for telephone pictionary"
    Value: !Sub "https://${TelephonePictionaryAPI}.execute-api.${AWS::Region}.amazonaws.com/${Env}"
